
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpetstore
  labels:
    app: jpetstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: jpetstore
        image: onek0708/jpetstore:v1
        ports:
        - containerPort: 80
          name: nginx
        - containerPort: 22
          name: sshd
        - containerPort: 8080
          name: tomcat
