apiVersion: v1
kind: Service
metadata:
  name: jpetstore
spec:
  selector:
    app: jpetstore
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
    - name: tomcat
      protocol: TCP
      port: 8080
      targetPort: 8080
